export default {
  //bottom
  HOME_SCREEN: 'HOME_SCREEN',
  ACTIVITY_SCREEN: 'ACTIVITY_SCREEN',
  MESSAGE_SCREEN: 'MESSAGE_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  //root main
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',
  //common
  VOUCHER: 'VOUCHER',
};
